/**********************************************************************************************************/
/* Code to create baseline comorbidity score: inclusion criteria will be women with a combined comorbidity score <1 (J Clin Epidemiology 64:749)  */
/* Before computing the score, I will use the ruleout rules provided by SEER-Medicare to compute their    */
/* comorbidity score   											  */
/* The linked files are generated by c09:   								  */
/**********************************************************************************************************/


options mprint notes compress=yes;
libname mydata '/disk/agedisk3/medicare.work/newhouse-DUA25730/xabi/BC_screening/data/';
libname anndata '/disk/agedisk3/medicare.work/newhouse-DUA25730/xabi/BC_screening/data/annals_review';



%macro cann06(agein= , daysbeforeinclusion= , debugging=);

proc printto print="/disk/agedisk3/medicare.work/newhouse-DUA25730/xabi/BC_screening/programs/CODES_FOR_ANNALS_REVIEW/cann06_logsANDlsts/cann06_comorbidity_score&agein..lst" new; run;
proc printto log="/disk/agedisk3/medicare.work/newhouse-DUA25730/xabi/BC_screening/programs/CODES_FOR_ANNALS_REVIEW/cann06_logsANDlsts/cann06_comorbidity_score&agein..log" new; run;

libname op1999 '/disk/aging/medicare/data/20pct/op/1999';libname op2000 '/disk/aging/medicare/data/20pct/op/2000';
libname op2001 '/disk/aging/medicare/data/20pct/op/2001';libname op2002 '/disk/aging/medicare/data/20pct/op/2002';
libname op2003 '/disk/aging/medicare/data/20pct/op/2003';libname op2004 '/disk/aging/medicare/data/20pct/op/2004';
libname op2005 '/disk/aging/medicare/data/20pct/op/2005';libname op2006 '/disk/aging/medicare/data/20pct/op/2006';
libname op2007 '/disk/aging/medicare/data/20pct/op/2007';

libname ip1999 '/disk/aging/medicare/data/20pct/ip/1999';libname ip2000 '/disk/aging/medicare/data/20pct/ip/2000';
libname ip2001 '/disk/aging/medicare/data/20pct/ip/2001';libname ip2002 '/disk/aging/medicare/data/20pct/ip/2002';
libname ip2003 '/disk/aging/medicare/data/20pct/ip/2003';libname ip2004 '/disk/aging/medicare/data/20pct/ip/2004';
libname ip2005 '/disk/aging/medicare/data/20pct/ip/2005';libname ip2006 '/disk/aging/medicare/data/20pct/ip/2006';
libname ip2007 '/disk/aging/medicare/data/20pct/ip/2007';

libname car1999 '/disk/aging/medicare/data/20pct/car/1999'  inencoding=any;
libname car2000 '/disk/aging/medicare/data/20pct/car/2000'  inencoding=any;
libname car2001 '/disk/aging/medicare/data/20pct/car/2001'  inencoding=any;
libname car2002 '/disk/aging/medicare/data/20pct/car/2002'  inencoding=any;
libname car2003 '/disk/aging/medicare/data/20pct/car/2003'  inencoding=any;
libname car2004 '/disk/aging/medicare/data/20pct/car/2004'  inencoding=any;
libname car2005 '/disk/aging/medicare/data/20pct/car/2005'  inencoding=any;
libname car2006 '/disk/aging/medicare/data/20pct/car/2006'  inencoding=any;
libname car2007 '/disk/aging/medicare/data/20pct/car/2007'  inencoding=any;



/* 
How years/claims are linked:

year inclusion /year claim ->	1999	2000	2001	2002	2003	2004	2005	2006	2007	2008

2000							x		x																
2001							x		x		x														
2002							x		x		x		x												
2003							x		x		x		x		x										
2004							x		x		x		x		x		x								
2005									x		x		x		x		x		x						
2006											x		x		x		x		x		x						
2007													x		x		x		x		x		x		

*/



/* minimacro to extract the inclusions corresponding to specific years -see above- that will have to be linked to the claims */
data x; 
length year 3; 
set mydata.box5_age&agein;  /* x */ ;
inclusion_date=startfup; 
year=year(inclusion_date); 
keep bene_id ehic inclusion_date year;run;
proc freq data=x; table year /missing; run;


%macro yearendoc();
%do j=1999 %to 2007; /* range of claims years which the included individuals will be linked to */
data e&j; set x; 
%let ub=min(2007,&j+5); 
if &j<=year<=&ub; run;
proc freq data=e&j; table year /missing;
title "claims from &j are linked patients included in these years"; %end; run;
%mend;
%yearendoc();


/* macro to create a long format "r" file from those years in a wide format: in op these are 1999-2000 */
%macro runpostillarun(varout= ,varin=, data= );
data &data (keep=ehic bene_id &varout i LINK_NUM FROM_DT THRU_DT);
set &data._pre (keep=ehic bene_id &varin.1-&varin.45 LINK_NUM FROM_DT THRU_DT);
array h{45} &varin.1-&varin.45;
do i=1 to 45;
	&varout=h[i];
output &data;
end;
run;
data &data;set &data;
if &varout ne '';
drop i; run;
proc sort data=&data nodupkey; by ehic THRU_DT hcpcs_cd;
%mend;


%macro bildu_car(daysbeforeinclusion= , agein=);

proc sort data=e1999; by ehic;run;

data C_e04_carc1999 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd4=icd_dgns_cd1-icd_dgns_cd4)); 
length dgns_cd1-dgns_cd4 pdgns_cd $7 from_dt thru_dt 5 ;
merge e1999 (in=a) car1999.cari1999  
(keep=ehic CARRCNTL pdgns_cd dgns_cd1-dgns_cd4 from_dt thru_dt &debugging  );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e04_carr1999 ; 
merge e1999 (in=a) car1999.cari1999
(keep=ehic CARRCNTL hcpcs_cd from_dt thru_dt &debugging  );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;


/* 2000: claims from 2000 link to inclusions from 2000-2001 (contained in e2000) */
proc sort data=e2000; by ehic;run;

data C_e0405_carc2000 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd4=icd_dgns_cd1-icd_dgns_cd4)); 
length dgns_cd1-dgns_cd4 pdgns_cd $7 from_dt thru_dt 5 ;
merge e2000 (in=a) car2000.car2000  
(keep=ehic CARRCNTL pdgns_cd dgns_cd1-dgns_cd4 from_dt thru_dt  &debugging  );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e0405_carr2000 ; 
merge e2000 (in=a) car2000.car2000
(keep=ehic CARRCNTL hcpcs_cd from_dt thru_dt &debugging  );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;





/* 2001: claims from 2001 link to inclusions from 2000-2002 (contained in e2001) */
proc sort data=e2001; by ehic;run;

data C_e0406_carc2001 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd4=icd_dgns_cd1-icd_dgns_cd4)); 
length dgns_cd1-dgns_cd4 pdgns_cd $7 from_dt thru_dt 5 ;
merge e2001 (in=a) car2001.car2001  
(keep=ehic CARRCNTL pdgns_cd dgns_cd1-dgns_cd4 from_dt thru_dt  &debugging  );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e0406_carr2001 ; 
merge e2001 (in=a) car2001.car2001
(keep=ehic CARRCNTL hcpcs_cd from_dt thru_dt &debugging  );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;




/* 2002: claims from 2002 link to inclusions from 2000-2003 (contained in e2002) */
proc sort data=e2002; by ehic;run;

data C_e0407_carc2002 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd4=icd_dgns_cd1-icd_dgns_cd4
sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd4 pdgns_cd $7 sfromdt sthrudt 5 ;
merge e2002 (in=a) car2002.carc2002  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd4 sfromdt sthrudt &debugging   );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt <= inclusion_date  ; run;

data R_e0407_carr2002 (rename=(sexpndt1=thru_dt)); 
merge e2002 (in=a) car2002.carl2002
(keep=ehic claimindex hcpcs_cd sexpndt1  &debugging  );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < sexpndt1 <= inclusion_date  ; run;



/* 2003: claims from 2003 link to inclusions from 2000 - 2004 (contained in e2003) */
proc sort data=e2003; by ehic;run;

data C_e0304_carc2003 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd4=icd_dgns_cd1-icd_dgns_cd4
sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd4 pdgns_cd $7 sfromdt sthrudt 5 ;
merge e2003 (in=a) car2003.carc2003  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd4 sfromdt sthrudt  &debugging  );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt <= inclusion_date  ; run;

data R_e0304_carr2003 (rename=(sexpndt1=thru_dt)); 
merge e2003 (in=a) car2003.carl2003
(keep=ehic claimindex hcpcs_cd sexpndt1  &debugging  );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < sexpndt1 <= inclusion_date  ; run;




/* 2004: claims from 2004 link to inclusions from 2000 - 2005 (contained in e2004) */
proc sort data=e2004; by ehic;run;

data C_e0405_carc2004 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd4=icd_dgns_cd1-icd_dgns_cd4
sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd4 pdgns_cd $7 sfromdt sthrudt 5 ;
merge e2004 (in=a) car2004.carc2004  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd4 sfromdt sthrudt  &debugging  );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt <= inclusion_date  ; run;

data R_e0405_carr2004 (rename=(sexpndt1=thru_dt)); 
merge e2004 (in=a) car2004.carl2004
(keep=ehic claimindex hcpcs_cd sexpndt1  &debugging  );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < sexpndt1 <= inclusion_date  ; run;


/* 2005: claims from 2005 link to inclusions from 2000 - 2006 (contained in e2005) */
proc sort data=e2005; by ehic;run;

data C_e0506_carc2005 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd4=icd_dgns_cd1-icd_dgns_cd4
sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd4 pdgns_cd $7 sfromdt sthrudt 5 ;
merge e2005 (in=a) car2005.carc2005  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd4 sfromdt sthrudt  &debugging  );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt <= inclusion_date  ; run;

data R_e0506_carr2005 (rename=(sexpndt1=thru_dt)); 
merge e2005 (in=a) car2005.carl2005
(keep=ehic claimindex hcpcs_cd sexpndt1  &debugging  );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < sexpndt1 <= inclusion_date  ; run;



/* 2006: claims from 2006 link to inclusions from 2000 - 2007 (contained in e2006) */
proc sort data=e2006; by bene_id;run;

data C_e0607_carc2006 (rename=(dgns_cd1-dgns_cd8=icd_dgns_cd1-icd_dgns_cd8)); 
length dgns_cd1-dgns_cd8 $7 from_dt thru_dt 5 ;
merge e2006 (in=a) car2006.carc2006  
(keep=bene_id clm_id dgns_cd1-dgns_cd8 from_dt thru_dt  &debugging  );
by bene_id;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e0607_carr2006; 
merge e2006 (in=a) car2006.carl2006
(keep=bene_id clm_id hcpcs_cd thru_dt  &debugging  );
by bene_id;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < thru_dt <= inclusion_date  ; run;


/* 2007: claims from 2007 link to inclusions from 2000 - 2007 (contained in e2007) */
proc sort data=e2007; by bene_id;run;

data C_e0708_carc2007 (rename=(dgns_cd1-dgns_cd8=icd_dgns_cd1-icd_dgns_cd8)); 
length dgns_cd1-dgns_cd8 $7 from_dt thru_dt 5 ;
merge e2007 (in=a) car2007.carc2007  
(keep=bene_id clm_id dgns_cd1-dgns_cd8 from_dt thru_dt  &debugging  );
by bene_id;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e0708_carr2007; 
merge e2007 (in=a) car2007.carl2007
(keep=bene_id clm_id hcpcs_cd thru_dt  &debugging  );
by bene_id;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < thru_dt <= inclusion_date  ; run;

/* FINAL POOLING OF ALL THE DATASETS */

data /*mydata.*/baseline_enrolled&agein._C_car_d&daysbeforeinclusion; set C_: ;
drop from_dt year claimindex clm_id  carrcntl ; run;
data /*mydata.*/baseline_enrolled&agein._R_car_d&daysbeforeinclusion; set R_: ;
drop year  claimindex carrcntl from_dt clm_id; run;

/* deleting all the temporay datasets because this program will be called from another */
proc datasets lib=work;
delete C_E04_CARC1999 C_E0405_CARC2000 C_E0406_CARC2001 C_E0407_CARC2002 C_E0304_carC2003 C_E0405_carC2004 
C_E0506_carC2005 C_E0607_carC2006 C_E0708_carC2007 
R_E04_CARR1999 R_E0405_CARR2000 R_E0406_CARR2001 R_E0407_CARR2002 R_E0304_carR2003 R_E0405_carR2004 
R_E0506_carR2005 R_E0607_carR2006 R_E0708_carR2007  
X;
run;

%mend; 

%bildu_car(daysbeforeinclusion=/*366*/&daysbeforeinclusion , agein=&agein );


%macro bildu_ip(daysbeforeinclusion= ,agein=);


/* 1999: claims from 1999 link to inclusions from 2000 (contained in e1999) */
proc sort data=e1999; by ehic;run;


data C_e04_ipc1999 (rename=(pdgns_cd=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdrdt1-prcdrdt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 pdgns_cd $7 prcdrdt1-prcdrdt6 from_dt thru_dt 5 ;
merge e1999 (in=a) ip1999.ip1999  
(keep=ehic CLM_CNTL pdgns_cd dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdrdt1-prcdrdt6 from_dt thru_dt &debugging );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;


data R_e04_ipr1999_pre; merge e1999 (in=a) ip1999.ip1999 	 
(keep=ehic CLM_CNTL FROM_DT THRU_DT hcpscd1-hcpscd58  &debugging );	
by ehic ;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;
run;

data R_e04_ipr1999 (keep=ehic bene_id hcpcs_cd i CLM_CNTL FROM_DT THRU_DT);
set R_e04_ipr1999_pre (keep=ehic bene_id hcpscd1-hcpscd58 CLM_CNTL FROM_DT THRU_DT );
array h{58} hcpscd1-hcpscd58;
do i=1 to 58;
	hcpcs_cd=h[i];
output  R_e04_ipr1999;
end;
run;

proc datasets lib=work; delete R_e04_ipr1999_pre; run;

data R_e04_ipr1999;set R_e04_ipr1999;
if hcpcs_cd ne '';
drop i; run;

proc sort data=R_e04_ipr1999 nodupkey; by ehic THRU_DT hcpcs_cd;


/* 2000: claims from 2000 link to inclusions from 2000-2001 (contained in e2000) */
proc sort data=e2000; by ehic;run;


data C_e0405_ipc2000 (rename=(pdgns_cd=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 from_dt thru_dt 5 ;
merge e2000 (in=a) ip2000.ip2000  
(keep=ehic link_num pdgns_cd dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdr_dt1-prcdr_dt6 from_dt thru_dt &debugging  );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;



data R_e0405_ipr2000_pre; merge e2000 (in=a) ip2000.ip2000 	
(keep=ehic LINK_NUM FROM_DT THRU_DT  hcpscd1-hcpscd45  &debugging );		
by ehic ;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;
run;

%runpostillarun(varout=hcpcs_cd, varin=hcpscd, data=R_e0405_ipr2000);

proc datasets lib=work;
delete R_e0405_ipr2000_pre;
run;




/* 2001: claims from 2001 link to inclusions from 2000-2002 (contained in e2001) */
proc sort data=e2001; by ehic;run;

data C_e0406_ipc2001 (rename=(pdgns_cd=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdrdt1-prcdrdt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 pdgns_cd $7 prcdrdt1-prcdrdt6 from_dt thru_dt 5 ;
merge e2001 (in=a) ip2001.ip2001  
(keep=ehic link_num pdgns_cd dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdrdt1-prcdrdt6 from_dt thru_dt  &debugging );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e0406_ipr2001_pre; merge e2001 (in=a) ip2001.ip2001 	
(keep=ehic LINK_NUM FROM_DT THRU_DT hcpscd1-hcpscd45  &debugging );		
by ehic ;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;
run;

%runpostillarun(varout=hcpcs_cd, varin=hcpscd, data=R_e0406_ipr2001);

proc datasets lib=work;
delete R_e0406_ipr2001_pre;
run;




/* 2002: claims from 2002 link to inclusions from 2000-2003 (contained in e2002) */
proc sort data=e2002; by ehic;run;

data C_e0407_ipc2002 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2002 (in=a) ip2002.ipc2002  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt  &debugging );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt <= inclusion_date  ; run;

data R_e0407_ipr2002 (rename=(srev_dt=thru_dt)); 
merge e2002 (in=a) ip2002.ipr2002
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt <= inclusion_date  ; run;



/* 2003: claims from 2003 link to inclusions from 2000 - 2004 (contained in e2003) */
proc sort data=e2003; by ehic;run;

data C_e0304_ipc2003 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2003 (in=a) ip2003.ipc2003  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt  &debugging );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt  <= inclusion_date ; run;

data R_e0304_ipr2003 (rename=(srev_dt=thru_dt)); 
merge e2003 (in=a) ip2003.ipr2003
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt  <= inclusion_date ; run;



/* 2004: claims from 2004 link to inclusions from 2000 - 2005 (contained in e2004) */
proc sort data=e2004; by ehic;run;

data C_e0405_ipc2004 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2004 (in=a) ip2004.ipc2004  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt  &debugging );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt  <= inclusion_date ; run;

data R_e0405_ipr2004 (rename=(srev_dt=thru_dt)); 
merge e2004 (in=a) ip2004.ipr2004
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt <= inclusion_date  ; run;




/* 2005: claims from 2005 link to inclusions from 2000 - 2006 (contained in e2005) */
proc sort data=e2005; by ehic;run;

data C_e0506_ipc2005 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2005 (in=a) ip2005.ipc2005  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt  &debugging );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt  <= inclusion_date ; run;

data R_e0506_ipr2005 (rename=(srev_dt=thru_dt)); 
merge e2005 (in=a) ip2005.ipr2005
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt <= inclusion_date  ; run;




/* 2006: claims from 2006 link to inclusions from 2000 - 2007 (contained in e2006) */
proc sort data=e2006; by bene_id;run;

data C_e0607_ipc2006 (rename=(ad_dgns=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6
prcdrdt1-prcdrdt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 ad_dgns $7 prcdrdt1-prcdrdt6 from_dt thru_dt 5 ;
merge e2006 (in=a) ip2006.ipc2006  
(keep=bene_id clm_id ad_dgns dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdrdt1-prcdrdt6 from_dt thru_dt  &debugging );
by bene_id;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e0607_ipr2006; 
merge e2006 (in=a) ip2006.ipr2006
(keep=bene_id clm_id hcpcs_cd thru_dt  &debugging );
by bene_id;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < thru_dt <= inclusion_date  ; run;




/* 2007: claims from 2007 link to inclusions from 2000 - 2007 (contained in e2007) */
proc sort data=e2007; by bene_id;run;

data C_e0708_ipc2007 (rename=(ad_dgns=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6
prcdrdt1-prcdrdt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 ad_dgns $7 prcdrdt1-prcdrdt6 from_dt thru_dt 5 ;
merge e2007 (in=a) ip2007.ipc2007  
(keep=bene_id clm_id ad_dgns dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdrdt1-prcdrdt6 from_dt thru_dt  &debugging );
by bene_id;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e0708_ipr2007; 
merge e2007 (in=a) ip2007.ipr2007
(keep=bene_id clm_id hcpcs_cd thru_dt  &debugging );
by bene_id;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < thru_dt <= inclusion_date  ; run;


/* FINAL POOLING OF ALL THE DATASETS */

data /*mydata.*/baseline_enrolled&agein._C_ip_d&daysbeforeinclusion; set C_: ;
drop from_dt year claimindex link_num clm_cntl clm_id ; run;
data /*mydata.*/baseline_enrolled&agein._R_ip_d&daysbeforeinclusion; set R_: ;
drop claimindex from_dt year link_num clm_id clm_cntl ; run;

proc datasets lib=work;
delete C_e04_ipc1999 C_e0405_ipc2000 C_e0406_ipc2001 C_e0407_ipc2002 C_E0304_ipC2003 C_E0405_ipC2004 
C_E0506_ipC2005 C_E0607_ipC2006 C_E0708_ipC2007 
R_e04_ipr1999_pre R_e04_ipr1999 R_e0405_ipr2000 R_e0406_ipr2001 R_e0407_ipr2002 R_E0304_ipR2003 R_E0405_ipR2004 
R_E0506_ipR2005 R_E0607_ipR2006 R_E0708_ipR2007 ;
run;

%mend; /* bildu_ip */


%bildu_ip(daysbeforeinclusion=/*366*/&daysbeforeinclusion ,agein=&agein);




%macro bildu_op(daysbeforeinclusion= ,agein=);




/* 1999: claims from 1999 link to inclusions from 2000 (contained in e1999) */
proc sort data=e1999; by ehic;run;

data C_e04_opc1999 (rename=(pdgns_cd=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdrdt1-prcdrdt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 pdgns_cd $7 prcdrdt1-prcdrdt6 from_dt thru_dt 5 ;
merge e1999 (in=a) op1999.op1999  
(keep=ehic link_num pdgns_cd dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdrdt1-prcdrdt6 from_dt thru_dt  &debugging    );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;


data R_e04_opr1999_pre; merge e1999 (in=a) op1999.op1999
(keep=ehic LINK_NUM FROM_DT THRU_DT hcpscd1-hcpscd45  &debugging     );	/* the structure of hcpcs in 2000 and 1999 is in "wide" format, thus the pain */
by ehic ;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;
run;

%runpostillarun(varout=hcpcs_cd, varin=hcpscd, data=R_e04_opr1999);

proc datasets lib=work;
delete R_e04_opr1999_pre;
run;

/* 2000: claims from 2000 link to inclusions from 2000-2001 (contained in e2000) */
proc sort data=e2000; by ehic;run;


data C_e0405_opc2000 (rename=(pdgns_cd=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdrdt1-prcdrdt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 pdgns_cd $7 prcdrdt1-prcdrdt6 from_dt thru_dt 5 ;
merge e2000 (in=a) op2000.op2000  
(keep=ehic link_num pdgns_cd dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdrdt1-prcdrdt6 from_dt thru_dt  &debugging    );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date ; run;



data R_e0405_opr2000_pre; merge e2000 (in=a) op2000.op2000 	/* linkage 2000 dx-2000 claims */ 
(keep=ehic LINK_NUM FROM_DT THRU_DT hcpscd1-hcpscd45   &debugging    );	/* the structure of hcpcs in 2000 and 1999 is in "wide" format, thus the pain */
by ehic ;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date ; run;
run;

%runpostillarun(varout=hcpcs_cd, varin=hcpscd, data=R_e0405_opr2000);

proc datasets lib=work;
delete R_e0405_opr2000_pre;
run;


/* 2001: claims from 2001 link to inclusions from 2000-2002 (contained in e2001) */
proc sort data=e2001; by ehic;run;

data C_e0406_opc2001 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2001 (in=a) op2001.opc2001  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt &debugging     );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt <= inclusion_date; run;

data R_e0406_opr2001 (rename=(srev_dt=thru_dt)); 
merge e2001 (in=a) op2001.opr2001
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging   );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt <= inclusion_date ; run;


/* 2002: claims from 2002 link to inclusions from 2000-2003 (contained in e2002) */
proc sort data=e2002; by ehic;run;

data C_e0407_opc2002 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2002 (in=a) op2002.opc2002  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt  &debugging    );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt  <= inclusion_date; run;

data R_e0407_opr2002 (rename=(srev_dt=thru_dt)); 
merge e2002 (in=a) op2002.opr2002
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging    );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt <= inclusion_date; run;


/* 2003: claims from 2003 link to inclusions from 2000 - 2004 (contained in e2003) */
proc sort data=e2003; by ehic;run;

data C_e0304_opc2003 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2003 (in=a) op2003.opc2003  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt  &debugging    );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt  <= inclusion_date; run;

data R_e0304_opr2003 (rename=(srev_dt=thru_dt)); 
merge e2003 (in=a) op2003.opr2003
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging    );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt  <= inclusion_date; run;


/* 2004: claims from 2004 link to inclusions from 2000 - 2005 (contained in e2004) */
proc sort data=e2004; by ehic;run;

data C_e0405_opc2004 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2004 (in=a) op2004.opc2004  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt  &debugging    );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt <= inclusion_date ; run;

data R_e0405_opr2004 (rename=(srev_dt=thru_dt)); 
merge e2004 (in=a) op2004.opr2004
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging    );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt <= inclusion_date ; run;


/* 2005: claims from 2005 link to inclusions from 2000 - 2006 (contained in e2005) */
proc sort data=e2005; by ehic;run;

data C_e0506_opc2005 (rename=(pdgns_cd=prncpal_dgns_cd dgns_cd1-dgns_cd10=icd_dgns_cd1-icd_dgns_cd10 prcdr_cd1-prcdr_cd6=icd_prcdr_cd1-icd_prcdr_cd6 prcdr_dt1-prcdr_dt6=prcdr_dt1-prcdr_dt6 sfromdt=from_dt sthrudt=thru_dt)); 
length dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 pdgns_cd $7 prcdr_dt1-prcdr_dt6 sfromdt sthrudt 5 ;
merge e2005 (in=a) op2005.opc2005  
(keep=ehic claimindex pdgns_cd dgns_cd1-dgns_cd10 prcdr_cd1-prcdr_cd6 prcdr_dt1-prcdr_dt6 sfromdt sthrudt  &debugging    );
by ehic;
if a;
if (inclusion_date-&daysbeforeinclusion) < sfromdt <= inclusion_date  ; run;

data R_e0506_opr2005 (rename=(srev_dt=thru_dt)); 
merge e2005 (in=a) op2005.opr2005
(keep=ehic claimindex hcpcs_cd srev_dt  &debugging    );
by ehic;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < srev_dt  <= inclusion_date ; run;



/* 2006: claims from 2006 link to inclusions from 2000 - 2007 (contained in e2006) */
proc sort data=e2006; by bene_id;run;

data C_e0607_opc2006 (rename=(ad_dgns=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6
prcdrdt1-prcdrdt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 ad_dgns $7 prcdrdt1-prcdrdt6 from_dt thru_dt 5 ;
merge e2006 (in=a) op2006.opc2006  
(keep=bene_id clm_id ad_dgns dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdrdt1-prcdrdt6 
from_dt thru_dt  &debugging    );
by bene_id;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt <= inclusion_date  ; run;

data R_e0607_opr2006; 
merge e2006 (in=a) op2006.opr2006
(keep=bene_id clm_id hcpcs_cd thru_dt  &debugging    );
by bene_id;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < thru_dt <= inclusion_date  ; run;



/* 2007: claims from 2007 link to inclusions from 2000 - 2007 (contained in e2007) */
proc sort data=e2007; by bene_id;run;

data C_e0708_opc2007 (rename=(ad_dgns=prncpal_dgns_cd dgnscd1-dgnscd10=icd_dgns_cd1-icd_dgns_cd10 prcdrcd1-prcdrcd6=icd_prcdr_cd1-icd_prcdr_cd6
prcdrdt1-prcdrdt6=prcdr_dt1-prcdr_dt6)); 
length dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 ad_dgns $7 prcdrdt1-prcdrdt6 from_dt thru_dt 5 ;
merge e2007 (in=a) op2007.opc2007  
(keep=bene_id clm_id ad_dgns dgnscd1-dgnscd10 prcdrcd1-prcdrcd6 prcdrdt1-prcdrdt6 
from_dt thru_dt  &debugging    );
by bene_id;
if a;
if (inclusion_date-&daysbeforeinclusion) < from_dt  <= inclusion_date ; run;

data R_e0708_opr2007; 
merge e2007 (in=a) op2007.opr2007
(keep=bene_id clm_id hcpcs_cd thru_dt  &debugging    );
by bene_id;
if a;
if hcpcs_cd ne '';
if (inclusion_date-&daysbeforeinclusion) < thru_dt <= inclusion_date  ; run;



/* FINAL POOLING OF ALL THE DATASETS */

data /*mydata.*/baseline_enrolled&agein._C_op_d&daysbeforeinclusion; set C_: ;
drop from_dt year claimindex link_num clm_id  ;run;

proc print data=baseline_enrolled&agein._C_op_d&daysbeforeinclusion (obs=20); run;


data /*mydata.*/baseline_enrolled&agein._R_op_d&daysbeforeinclusion; set R_: ;
drop claimindex from_dt year link_num clm_id  ;run;

proc print data=baseline_enrolled&agein._R_op_d&daysbeforeinclusion (obs=20); run;

/* deleting all the temporay datasets */
proc datasets lib=work;
delete C_e04_opc1999 C_e0405_opc2000 C_e0406_opc2001 C_e0407_opc2002 C_E0304_OPC2003 C_E0405_OPC2004 
C_E0506_OPC2005 C_E0607_OPC2006 C_E0708_OPC2007
R_e04_opr1999_pre R_e04_opr1999 R_e0405_opr2000 R_e0406_opr2001 R_e0407_opr2002 R_E0304_OPR2003 R_E0405_OPR2004 
R_E0506_OPR2005 R_E0607_OPR2006 R_E0708_OPR2007 ;
run;


%mend;

%bildu_op(daysbeforeinclusion=/*366*/ &daysbeforeinclusion ,agein=&agein);


%include './remove.ruleout.dxcodes.macro.sas';
%include './combined_comorbidity_score_code.sas';
%include './combined_comorbidity_score_code_hta_non_protective.sas';


data id_dates;
set mydata.box5_age&agein (keep=bene_id startfup);run;

proc sort data=id_dates; by bene_id;run;



data op&agein.c;
set baseline_enrolled&agein._c_op_d&daysbeforeinclusion (keep=bene_id thru_dt prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd10  inclusion_date);
clmdte=thru_dt;
array DX{11} $ dx1-dx11;
array DGN_CD{11} prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd10;
do i=1 to 11;   dx[i]=dgn_cd[i]; end;
filetype='O';
keep bene_id clmdte dx1-dx11 filetype inclusion_date;
run;

data op&agein.r;
set baseline_enrolled&agein._r_op_d&daysbeforeinclusion (keep=bene_id thru_dt hcpcs_cd inclusion_date );
clmdte=thru_dt;
filetype='O';
keep bene_id clmdte hcpcs_cd filetype inclusion_date;
run;

data op&agein; set op&agein.c op&agein.r; run;

proc sort data=op&agein; by bene_id; run;

proc datasets lib=work; delete op&agein.c op&agein.r ;run;



data ip&agein.c;
set baseline_enrolled&agein._c_ip_d&daysbeforeinclusion (keep=bene_id thru_dt prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd10 inclusion_date );
clmdte=thru_dt;
array DX{11} $ dx1-dx11;
array DGN_CD{11} prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd10;
do i=1 to 11;   dx[i]=dgn_cd[i]; end;
filetype='M';
keep bene_id clmdte dx1-dx11 filetype inclusion_date;
run;

data ip&agein.r;
set baseline_enrolled&agein._r_ip_d&daysbeforeinclusion (keep=bene_id thru_dt hcpcs_cd  inclusion_date );
clmdte=thru_dt;
filetype='M';
keep bene_id clmdte hcpcs_cd filetype inclusion_date;
run;

data ip&agein; set ip&agein.c ip&agein.r; run;
proc sort data=ip&agein; by bene_id; run;

proc datasets lib=work; delete ip&agein.c ip&agein.r ;run;


data car&agein.c;
set baseline_enrolled&agein._c_car_d&daysbeforeinclusion (keep=bene_id thru_dt prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd8  inclusion_date );
clmdte=thru_dt;
array DX{9} $ dx1-dx9;
array DGN_CD{9} prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd8;
do i=1 to 9;   dx[i]=dgn_cd[i]; end;
filetype='C';
keep bene_id clmdte dx1-dx9 filetype inclusion_date;
run;

data car&agein.r;
set baseline_enrolled&agein._r_car_d&daysbeforeinclusion (keep=bene_id thru_dt hcpcs_cd inclusion_date   );
clmdte=thru_dt;
filetype='C';
keep bene_id clmdte hcpcs_cd filetype inclusion_date;
run;

data car&agein; set car&agein.c car&agein.r; run;
proc sort data=car&agein; by bene_id; run;

proc datasets lib=work; delete car&agein.c car&agein.r ;run;

data all&agein;
set op&agein ip&agein car&agein;

finish=inclusion_date-1;
start=inclusion_date-&daysbeforeinclusion;

format start finish clmdte DATE9. ;
run;


proc print data=all&agein (obs=10); run;


proc sort data=all&agein; by bene_id; run;



%ruleout(setin=all&agein, patid=bene_id, clmdte=clmdte, start=start, finish=finish,
dxvarstr=dx1-dx11, ndxvar=11, hcpcs=hcpcs_cd, filetype=filetype);

data clmrecs; set clmrecs (keep=bene_id dx1-dx11);

proc print data=clmrecs (obs=20); title 'before transposing'; run;


/* man, I gotta do my own transposing */

%macro transpose(i= );
data trans&i;set clmrecs (keep=bene_id dx&i); ICD9variable=dx&i;drop dx&i;run;
%mend; /* transpose */
%do i=1 %to 11; %transpose(i=&i);%end;run; /* 11 is the number of icd9 fields */

data clmrecs;set trans: ; if ICD9variable ne ''; run;
proc datasets library=work; delete trans: ; run;
proc sort data=clmrecs; by bene_id; run;

proc print data=clmrecs (obs=20); title 'after transposing'; run;


%comcomscore(datain=clmrecs,uniqueidentifier=bene_id);
%comcomscore2(datain=clmrecs,uniqueidentifier=bene_id); /* this one calls in the score that does not consider HTA */

proc print data=combinedcomorbidityscore (obs=25); run;
proc print data=combinedcomorbidityscore_nohta (obs=25); run;

proc freq data=combinedcomorbidityscore; 
table combinedscore / missing; title "original score"; run;

proc freq data=combinedcomorbidityscore_nohta; 
table combinedscore2 / missing; title "modified score"; run;

proc sort data=mydata.box5_age&agein; by bene_id; run;

proc sort data=combinedcomorbidityscore; by bene_id; run;
proc sort data=combinedcomorbidityscore_nohta; by bene_id; run;

data box8_age&agein; 
merge mydata.box5_age&agein (in=a) combinedcomorbidityscore combinedcomorbidityscore_nohta; 
by bene_id; 
if a; 
run;

/*proc freq data=box8_age&agein; 
table combinedscore*combinedscore2 / missing; run;*/



data box8_age&agein;
length baseline_combinedscore baseline_combinedscore2 3 ; 
set box8_age&agein; 
baseline_combinedscore=combinedscore; 
if combinedscore=. then baseline_combinedscore=0; 
baseline_combinedscore2=combinedscore2; 
if combinedscore2=. then baseline_combinedscore2=0; 
drop combinedscore combinedscore2; 
run;


proc freq data=box8_age&agein; 
table baseline_combinedscore*baseline_combinedscore2 baseline_combinedscore baseline_combinedscore2 / missing; 
title 'numbers for box 7th, exclusion due to comorbidity score >  0'; 
run;


data anndata.box8_age&agein; 
set box8_age&agein; 
if .< baseline_combinedscore < 1; 
run;

proc freq data=anndata.box8_age&agein;
table baseline_combinedscore baseline_combinedscore2 / missing; 
run;


proc means data=anndata.box8_age&agein n; 
var baseline_combinedscore; 
title 'number of eligible people, box 8';
run; 

proc datasets lib=work kill memtype=data;run;


%mend; /* %cann06 */

*%cann06(agein=84, daysbeforeinclusion=1825, debugging= obs=100000);


