/**********************************************************************************************************/
/* Code to create a comorbidity score. I will use the combined score by DoPE: J Clin Epidemiology 64:749  */
/* Before computing the score, I will use the ruleout rules provided by SEER-Medicare to compute their    */
/* comorbidity score   											  */
/* The linked files are generated by cann09* and deleted at the end of this program						  */
/**********************************************************************************************************/


options mprint notes compress=yes;
/*libname mydata '/disk/agedisk3/medicare.work/newhouse-DUA25730/xabi/BC_screening/data/';*/

libname anndata '/disk/agedisk3/medicare.work/newhouse-DUA25730/xabi/BC_screening/data/annals_review';


%macro cann11(agein=);

proc printto print="/disk/agedisk3/medicare.work/newhouse-DUA25730/xabi/BC_screening/programs/CODES_FOR_ANNALS_REVIEW/cann11_logsANDlsts/cann11_comorbidity_score&agein..lst" new; run;
proc printto log="/disk/agedisk3/medicare.work/newhouse-DUA25730/xabi/BC_screening/programs/CODES_FOR_ANNALS_REVIEW/cann11_logsANDlsts/cann11_comorbidity_score&agein..log" new; run;


%macro comorb(agein= );

%include './remove.ruleout.dxcodes.macro.sas';
%include './combined_comorbidity_score_code_tv.sas';

proc contents data=anndata.enrolled&agein._c_op_d366;run;
proc contents data=anndata.enrolled&agein._c_ip_d366;run;
proc contents data=anndata.enrolled&agein._c_car_d366;run;
proc contents data=anndata.enrolled&agein._r_car_d366;run;

data id_dates;
set anndata.box8_baseline&agein (keep=bene_id startfup);run;

proc sort data=id_dates; by bene_id;run;


/*proc print data=anndata.enrolled&agein._r_op_d366 (obs=10000);run;
%return;*/

/* outpatient, do outside the loop */

data op&agein.c;
set anndata.enrolled&agein._c_op_d366 (keep=bene_id thru_dt prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd10   /* obs=100000 */     );
clmdte=thru_dt;
array DX{11} $ dx1-dx11;
array DGN_CD{11} prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd10;
do i=1 to 11;   dx[i]=dgn_cd[i]; end;
filetype='O';
keep bene_id clmdte dx1-dx11 filetype;
run;

data op&agein.r;
set anndata.enrolled&agein._r_op_d366 (keep=bene_id thru_dt hcpcs_cd   /* obs=100000 */     );
clmdte=thru_dt;
filetype='O';
keep bene_id clmdte hcpcs_cd filetype;
run;

data op&agein; set op&agein.c op&agein.r; run;

proc sort data=op&agein; by bene_id; run;

proc datasets lib=work; delete op&agein.c op&agein.r ;run;

/*proc print data=op&agein (obs=10000);run;
%return;*/


/* inpatient, do outside the loop */

data ip&agein.c;
set anndata.enrolled&agein._c_ip_d366 (keep=bene_id thru_dt prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd10   /* obs=100000 */     );
clmdte=thru_dt;
array DX{11} $ dx1-dx11;
array DGN_CD{11} prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd10;
do i=1 to 11;   dx[i]=dgn_cd[i]; end;
filetype='M';
keep bene_id clmdte dx1-dx11 filetype;
run;

data ip&agein.r;
set anndata.enrolled&agein._r_ip_d366 (keep=bene_id thru_dt hcpcs_cd   /* obs=100000 */     );
clmdte=thru_dt;
filetype='M';
keep bene_id clmdte hcpcs_cd filetype;
run;

data ip&agein; set ip&agein.c ip&agein.r; run;
proc sort data=ip&agein; by bene_id; run;

/*proc print data=ip&agein (obs=10000);run;
%return;*/

proc datasets lib=work; delete ip&agein.c ip&agein.r ;run;


/* carrier, do outside the loop */

data car&agein.c;
set anndata.enrolled&agein._c_car_d366 (keep=bene_id thru_dt prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd8   /* obs=100000 */     );
clmdte=thru_dt;
array DX{9} $ dx1-dx9;
array DGN_CD{9} prncpal_dgns_cd icd_dgns_cd1-icd_dgns_cd8;
do i=1 to 9;   dx[i]=dgn_cd[i]; end;
filetype='C';
keep bene_id clmdte dx1-dx9 filetype;
run;

data car&agein.r;
set anndata.enrolled&agein._r_car_d366 (keep=bene_id thru_dt hcpcs_cd   /* obs=100000 */     );
clmdte=thru_dt;
filetype='C';
keep bene_id clmdte hcpcs_cd filetype;
run;

data car&agein; set car&agein.c car&agein.r; run;
proc sort data=car&agein; by bene_id; run;

/*proc print data=car&agein (obs=10000);run;
%return;*/


proc datasets lib=work; delete car&agein.c car&agein.r ;run;



%macro comorb_month(month= );

data all&agein.w&month;
set op&agein ip&agein car&agein;

finish=INTNX( 'MONTH', mdy(1,1,1999), &month+11, 'SAME' );
start=INTNX( 'MONTH', mdy(1,1,1999), &month-1, 'SAME' );

format start finish clmdte DATE9. ;
run;


proc sort data=all&agein.w&month; by bene_id; run;

/*proc print data=all&agein.w&month (obs=5000);run;
%return;*/


%ruleout(setin=all&agein.w&month, patid=bene_id, clmdte=clmdte, start=start, finish=finish,
dxvarstr=dx1-dx11, ndxvar=11, hcpcs=hcpcs_cd, filetype=filetype);

/*proc print data=clmrecs (obs=3000);format clmdte date9.; run;
%return;*/

data clmrecs; set clmrecs (keep=bene_id dx1-dx11);

/*proc print data=clmrecs (obs=30);run;*/

/* man, I gotta do my own transposing */

%macro transpose(i= );
data trans&i;set clmrecs (keep=bene_id dx&i); ICD9variable=dx&i;drop dx&i;run;
%mend; /* transpose */
%do i=1 %to 11; %transpose(i=&i);%end;run; /* 11 is the number of icd9 fields */

data clmrecs&month;set trans: ; if ICD9variable ne ''; run;
proc datasets library=work; delete trans: ; run;
proc sort data=clmrecs&month; by bene_id; run;

/*proc print data=clmrecs&month (obs=1000);run;*/


%comcomscore(datain=clmrecs&month,uniqueidentifier=bene_id, month=&month);

/*proc print data=combinedcomorbidityscore&week (obs=20);run;*/

data combinedcomorbidityscore&month ;length combinedscore&month 3;
set combinedcomorbidityscore&month ;
combinedscore&month=combinedscore;drop combinedscore;run;

proc sort data=combinedcomorbidityscore&month ;by bene_id; run;

proc datasets library=work; delete conditionweights clmrecs: cond: id_dates all: ; run;

%mend; /* %comorb_week */

%do month=1 %to 108;
%comorb_month(month=&month);
%end;


data anndata.combinedcomorb&agein;
merge combinedcomorbidityscore: ;
by bene_id; 
run;

proc datasets lib=work; delete combinedcomorbidityscore: car: ip: op: ; run;

proc datasets lib=anndata; delete enrolled&agein._: ; run;

proc print data=anndata.combinedcomorb&agein (obs=200);

proc contents data=anndata.combinedcomorb&agein;run;

%mend; /* %comorb */


%comorb(agein=&agein);


%mend; /* %c11 */

/*%cann11(agein=84);*
%cann11(agein=70);
%cann11(agein=71);
%cann11(agein=76);
%cann11(agein=77);
%cann11(agein=72);*/

